spring:
  application:
    name: gateway-service

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: auth-service
      stripPrefix: false
      sensitiveHeaders:

    department-service:
      path: /department/**
      serviceId: department-service
      stripPrefix: false
      sensitiveHeaders:

    registration-service:
      path: /registration/**
      serviceId: registration-service
      stripPrefix: false
      sensitiveHeaders:

ribbon:
  ReadTimeout: 60000

server:
  port: 8080