package ru.shaplov.shop.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://service.shop.shaplov.ru/", name = "ShopService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ShopService {

    @WebMethod
    @Action(input = "http://service.shop.shaplov.ru/ShopService/updateRequest", output = "http://service.shop.shaplov.ru/ShopService/updateResponse")
    public void update(

        @WebParam(partName = "arg0", name = "arg0")
        Item arg0
    );

    @WebMethod
    @Action(input = "http://service.shop.shaplov.ru/ShopService/findByIdRequest", output = "http://service.shop.shaplov.ru/ShopService/findByIdResponse")
    @WebResult(name = "return", targetNamespace = "http://service.shop.shaplov.ru/", partName = "return")
    public Item findById(

        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );

    @WebMethod
    @Action(input = "http://service.shop.shaplov.ru/ShopService/creteRequest", output = "http://service.shop.shaplov.ru/ShopService/creteResponse")
    @WebResult(name = "return", targetNamespace = "http://service.shop.shaplov.ru/", partName = "return")
    public Item crete(

        @WebParam(partName = "arg0", name = "arg0")
        Item arg0
    );

    @WebMethod
    @Action(input = "http://service.shop.shaplov.ru/ShopService/listRequest", output = "http://service.shop.shaplov.ru/ShopService/listResponse")
    @WebResult(name = "return", targetNamespace = "http://service.shop.shaplov.ru/", partName = "return")
    public ItemArray list()
;

    @WebMethod
    @Action(input = "http://service.shop.shaplov.ru/ShopService/deleteRequest", output = "http://service.shop.shaplov.ru/ShopService/deleteResponse")
    public void delete(

        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );
}
