package ru.shaplov.shop.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "ShopServiceImplService",
                  wsdlLocation = "shop.wsdl",
                  targetNamespace = "http://service.shop.shaplov.ru/")
public class ShopServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.shop.shaplov.ru/", "ShopServiceImplService");
    public final static QName ShopServiceImplPort = new QName("http://service.shop.shaplov.ru/", "ShopServiceImplPort");
    static {
        URL url = ShopServiceImplService.class.getResource("shop.wsdl");
        if (url == null) {
            url = ShopServiceImplService.class.getClassLoader().getResource("shop.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(ShopServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "shop.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShopServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShopServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ShopServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ShopServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ShopServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShopServiceImplPort")
    public ShopService getShopServiceImplPort() {
        return super.getPort(ShopServiceImplPort, ShopService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShopServiceImplPort")
    public ShopService getShopServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ShopServiceImplPort, ShopService.class, features);
    }

}
